name: Publish Site Changes

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Install dependencies
      run: dotnet restore /nologo
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release --no-restore /nologo
      working-directory: src
    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal /nologo
      working-directory: src
    - name: Publish
      run: dotnet publish --no-restore --verbosity normal /nologo /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DesktopBuildPackageLocation="../../package/package.zip"
      working-directory: src
